export const REFRESH_SUBJECTS = 'REFRESH_SUBJECTS'
export const REFRESH_COLLABORATOR = 'REFRESH_COLLABORATOR'
export const REFRESH_CATEGORIES = 'REFRESH_CATEGORIES'
export const REFRESH_CHANNELS = 'REFRESH_CHANNELS'

export const FILTER_CATEGORY = 'FILTER_CATEGORY'
export const FILTER_CHANNEL = 'FILTER_CHANNEL'
export const FILTER_TAB = 'FILTER_TAB'
